package org.jbomberman.utils;

public enum UpdateType {
    U_BLOCK_DESTROYED,
    U_POSITION,
    GAME_WIN,
    U_PU_BOMB,
    LESS_LIFE,
    MORE_LIFE,
    ENEMY_POSITION_CHANGED,
    U_ENEMY_DEAD,
    BOMB_RELEASED,
    PAUSE,
    END_PAUSE, GAME_EXIT, PROFILE_LOADER, LOAD_FIXED_BLOCKS, L_ENEMIES, LOAD_RANDOM_BLOCKS, L_PLAYER, LOAD_GROUND, L_MAP, GAME_OVER
}