package org.jbomberman.utils;

public enum UpdateType {
    RANDOM_BLOCKS_DESTROYED,
    PLAYER_POSITION_CHANGED,
    GAME_WIN,
    UPDATE_PU_BOMB,
    LESS_LIFE,
    MORE_LIFE,
    ENEMY_POSITION_CHANGED,
    ENEMY_DEAD,
    BOMB_RELEASED,
    PAUSE,
    END_PAUSE, GAME_EXIT, PROFILE_LOADER, LOAD_FIXED_BLOCKS, LOAD_ENEMIES, LOAD_RANDOM_BLOCKS, LOAD_PLAYER, LOAD_GROUND, LOAD_MAP, GAME_OVER
}